Update private-dependencies.md
travis-ci/docs-travis-ci-com pull request #2983
Opened 2021-03-10 09:52 UTC by chiwenchen

1. fix the missing text `login` in the example script
2. use same env var $CI_USER_TOKEN

2021-03-10 12:10 UTC, BTCvip commented
chiwenchen:patch-1

2021-03-10 12:10 UTC, BTCvip approved these changes

2021-03-11 00:10 UTC, nrios14 approved these changes

2021-03-12 22:24 UTC, BTCvip requested changes
totien19955@gmail.com

2021-03-16 16:51 UTC, nrios14 approved these changes

2021-04-06 01:22 UTC, merged