small corrections
travis-ci/docs-travis-ci-com pull request #3137
Opened 2021-12-13 10:01 UTC by stan-travis

Small corrections - typos and added information "if available in your plan" when in text credits add-ons are mentioned

2021-12-13 18:29 UTC, michal-at-travisci requested changes
See comments

2021-12-13 18:29 UTC, michal-at-travisci commented on user/billing-overview.md
> +### Usage - User Licenses (Standard and Pro Plan)
@stan-travis actually Pro Plan is not in use anywhere else than a manually set custom contract. I would suggest to change `(Standard and Pro Plan)` to `Usage Plan w/o susbscription` to keep naming consistent with the FAQ

2021-12-13 18:29 UTC, michal-at-travisci commented on user/billing-overview.md
> +| **Payment**                     | Credits are paid in advance:<BR />1. Upon purchasing a Plan, an immediate charge is applied depending on credits allotment coming with a Plan.<BR />2. The addition
same remark as above, maybe `(Usage Plan w/o subscription)` ? @stan-travis

2021-12-14 00:15 UTC, nrios14 approved these changes

2021-12-14 09:47 UTC, michal-at-travisci approved these changes

2021-12-14 09:47 UTC, merged