Update open_source_licence.md
travis-ci/docs-travis-ci-com pull request #3364
Opened 2024-04-22 13:57 UTC by michal-at-travisci

Changed the title and added content.
In current form this document puzzles users: why, what, what for is this published in the documentation site. Publishing simply ember.js license gives no understanding and on top of that what piece of software the licensing applies to in the Cloud environment.

2024-04-22 14:08 UTC, nrios14 requested changes
Title: Licensing Information (capitalize the "I")
* Open-Source - add a hyphen.
*  "is usually licensed under the MIT License." --> switch "with" to "under the"
* assessment --> is missing an "s"
* the EMberJS --> add "the"

2024-04-22 14:53 UTC, merged

2024-05-02 17:57 UTC, hhjmmmmmmmm approved these changes

2024-05-02 17:57 UTC, hhjmmmmmmmm approved these changes

2024-05-02 17:57 UTC, hhjmmmmmmmm approved these changes

2024-05-03 05:24 UTC, hhjmmmmmmmm approved these changes

2024-05-03 05:24 UTC, hhjmmmmmmmm approved these changes

2024-05-03 05:24 UTC, hhjmmmmmmmm approved these changes

2024-05-03 05:24 UTC, hhjmmmmmmmm approved these changes

2024-05-03 05:24 UTC, hhjmmmmmmmm approved these changes

2024-05-03 05:24 UTC, hhjmmmmmmmm approved these changes

2024-05-03 05:25 UTC, hhjmmmmmmmm approved these changes

2024-05-03 05:25 UTC, hhjmmmmmmmm approved these changes

2024-05-03 05:25 UTC, hhjmmmmmmmm approved these changes

2024-05-03 05:26 UTC, hhjmmmmmmmm approved these changes

2024-05-03 05:26 UTC, hhjmmmmmmmm approved these changes